### ISSUE TITLE
allow firehose view without authentication?

### ISSUE THREAD

**Issue by joshblum** [haystack/eyebrowse-server#105]
right now you can just use the api to request data, should we allow the firehose without authentication?

**Comment by amyxzhang** [comment]
I'm not sure. I think yes.....although I didn't enable it before, because I
checked on Facebook and Twitter to see if I could view public streams (not
people's profiles but hashtags or searching) and was unable to without
logging in. You can already see people's profiles without logging btw.
Perhaps this is a way that FB and Twitter try to get people to sign up for
an account?

On Sat, May 16, 2015 at 5:15 PM, Joshua Blum <notifications@github.com>
wrote:

> right now you can just use the api to request data, should we allow the
> firehose without authentication?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haystack/eyebrowse-server/issues/105>.
>



-- 
Amy X. Zhang | Ph.D. student at MIT CSAIL | http://people.csail.mit.edu/axz
| @amyxzh

**Comment by karger** [comment]
I think yes.   Twitter etc block it to make money which we aren't trying for.   We could limit access to certain "value added" analytics, but not sure there's a point.   Getting people registered accomplishes little if they don't install the extension.   I guess it gives us an email address to nag... 

<div>-------- Original message --------</div><div>From: Joshua Blum <notifications@github.com> </div><div>Date:05/16/2015  5:15 PM  (GMT-05:00) </div><div>To: haystack/eyebrowse-server <eyebrowse-server@noreply.github.com> </div><div>Cc:  </div><div>Subject: [eyebrowse-server] allow firehose view without authentication? (#105) </div><div>
</div>right now you can just use the api to request data, should we allow the firehose without authentication?

**Comment by joshblum** [comment]
I think its useful as a demo when you're showing the site to people more
than just showing your profile
