### ISSUE TITLE
improve ranking/recommendation algorithm

### ISSUE THREAD

**Issue by amyxzhang** [haystack/eyebrowse-server#136]
Our ranking could be way better!

I'm sure there is some literature on how to do this properly. need recsys lit review.

First step:
downrank things that are commonly viewed (while upranking things that are "hot" - viewed by many people recently but not normally)

Then personalization:
uprank things that I might like - based on my click history from eyebrowse and based on my own eyebrowse history (focusing on domains, title keywords). More emphasized towards click history.

If the click history data is small, can look at click history of followees as well. 
If eyebrowse history is small, look at eyebrowse history of followees.

When using eyebrowse history for this part, will need to again discount domains I go to a lot, keywords seen a lot.

**Comment by amyxzhang** [comment]
Thought: use Kibitz for recommendation?

**Comment by JohnHHu** [comment]
I have toyed around with the score and think it appears better now.
- I made recency more important.
- I tried to discount pages from domains that are extremely popular (pushing down stackoverflow, github, and wikipedia pages). 
- I tried to *not* do that for specifically article-type domains since from our study, most people seemed to click on articles from the feed. Right now, it's just a manual list consisting only of nytimes (seems the rest aren't heavily trafficked domains so the discounting didn't seem to really hurt their scores). 
- I tried to discount pages to domain home pages that were heavily visited (like nytimes home page, etc.)
- Because of time tracking bugs, we get very old visits that have a really long amt of time spent (usually in error) lingering at the top. I set a cutoff for time so that these don't get scored too highly.

**Comment by amyxzhang** [comment]
Sorry that was accidentally posted from my boyfriend's github acct! ^_^

**Comment by JohnHHu** [comment]
Huh?

**Comment by amyxzhang** [comment]
Closing this for now.
